env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - node
  - import
  - simple-import-sort
rules:
  import/extensions: off
  import/first: error
  import/newline-after-import: error
  import/no-duplicates: error
  import/no-extraneous-dependencies: off
  import/prefer-default-export: off
  no-console: off
  no-underscore-dangle: off
  no-unused-expressions:
    - error
    - allowShortCircuit: true
  no-unused-vars: off
  simple-import-sort/exports: error
  simple-import-sort/imports: error
